### ISSUE TITLE
Add composer diag

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/composer-cheatsheet#4]
The command `composer diag` rox,

also a section about "how to resolve an issue", about diagnostic & fixing should be added.

**Comment by stof** [comment]
The command is there (its real name is `composer diagnose`, `diag` only relies on the Symfony Console shortcutting possibilities)

**Comment by damienalexandre** [comment]
Yes, command introduced in 4e78f881f7c4de7521be0f79445fd5781a1a2f1b - I've forgot to close the issue, thx!
